# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-01 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branchcode', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bankcode', models.CharField(max_length=50)),
                ('bankacc', models.IntegerField()),
                ('bankaccname', models.CharField(max_length=50)),
                ('transactiondate', models.DateTimeField()),
                ('costcenter', models.CharField(max_length=10)),
                ('glcode', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
                ('currency', models.CharField(default='RM', max_length=2)),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
