# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_auto_20181004_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseclaim',
            name='bankcode',
            field=models.CharField(choices=[(b'HLBBMYKL', b'Hong Leong bank'), (b'RHBBMYKL', b'RHB Bank'), (b'HBMBMYKL', b'HSBC Bank'), (b'DEUTMYKL', b'Deutsche Bank'), (b'MFBBMYKL', b'Maybank'), (b'CIBBMYKL', b'CIMB bank'), (b'UOVBMYKL', b'UOB Bank'), (b'PBBEMYKL', b'Public Bank'), (b'OCBCMYKL', b'OCBC Bank'), (b'ARBKMYKL', b'AmBank')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='glcode',
            field=models.CharField(choices=[(4165, b'Staff Reimbursement Mobile'), (4190, b'Postage'), (4191, b'Couriers'), (4200, b'Stationery'), (4311, b'International Fares'), (4312, b'Internation Accomodation'), (4313, b'International Expense'), (4321, b'Local Fares')], max_length=100, null=True),
        ),
    ]
